const app=document.querySelector('#app'),account=document.querySelector('#account'),err=document.querySelector('#error'),lightbox=document.querySelector('#lightbox'),lightboxImage=document.querySelector('#lightboxImage'),lightboxMeta=document.querySelector('#lightboxMeta'),lightboxPrev=document.querySelector('#lightboxPrev'),lightboxNext=document.querySelector('#lightboxNext');
let S={repo:null,branch:null,run:null,artifact:null},currentImages=[],lightboxIndex=0,navigatingHistory=false;
async function api(url){err.textContent='';const r=await fetch(url);if(r.status===401){renderLogin();throw new Error('AUTH')}const d=await r.json();if(!r.ok)throw new Error(d.error||JSON.stringify(d));return d}
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function enc(v){return encodeURIComponent(String(v)).replace(/'/g,'%27')}
function pack(v){return encodeURIComponent(JSON.stringify(v)).replace(/'/g,'%27')}
window.pickRepoEncoded=v=>window.pickRepo(decodeURIComponent(v));window.pickBranchEncoded=v=>window.pickBranch(decodeURIComponent(v));window.pickRunEncoded=v=>window.pickRun(JSON.parse(decodeURIComponent(v)));window.pickArtifactEncoded=v=>window.pickArtifact(JSON.parse(decodeURIComponent(v)));
function ago(d){const n=(Date.now()-new Date(d))/1000;if(n<60)return`${Math.max(0,Math.floor(n))}s ago`;if(n<3600)return`${Math.floor(n/60)}m ago`;if(n<86400)return`${Math.floor(n/3600)}h ago`;return`${Math.floor(n/86400)}d ago`}
function statusClass(s=''){return s==='success'?'success':s==='failure'?'failure':''}
function pathFor(){if(!S.repo)return'/';const[o,r]=S.repo.split('/');let p=`/repo/${encodeURIComponent(o)}/${encodeURIComponent(r)}`;if(S.branch)p+=`/branch/${encodeURIComponent(S.branch)}`;if(S.run)p+=`/run/${encodeURIComponent(S.run.id)}`;if(S.artifact)p+=`/artifact/${encodeURIComponent(S.artifact.id)}`;return p}
function setRoute(replace=false){if(navigatingHistory)return;const p=pathFor();if(location.pathname!==p)history[replace?'replaceState':'pushState']({},'',p)}
function parseRoute(){const p=location.pathname.split('/').filter(Boolean).map(decodeURIComponent);if(!p.length)return{};if(p[0]!=='repo'||p.length<3)return{};const r={repo:`${p[1]}/${p[2]}`};for(let i=3;i<p.length;){if(p[i]==='branch'&&p[i+1]){r.branch=p[i+1];i+=2}else if(p[i]==='run'&&p[i+1]){r.runId=p[i+1];i+=2}else if(p[i]==='artifact'&&p[i+1]){r.artifactId=p[i+1];i+=2}else break}return r}
function renderLogin(){account.innerHTML='';app.innerHTML=`<div class="login-panel"><h2>Sign in with GitHub</h2><p class="muted">Artifact Lens turns GitHub Actions artifacts into a browsable media gallery. Pick an installed repository, choose a branch and workflow run, then inspect the files produced by CI without downloading and unpacking ZIP files yourself.</p><div class="file-types"><div class="file-type"><strong>Images</strong><span class="muted">PNG, JPEG, GIF, WebP and SVG are shown inline. Click an image for a lightbox; use previous/next when the artifact contains multiple images.</span></div><div class="file-type"><strong>Video & audio</strong><span class="muted">MP4, WebM, MOV, MP3, WAV and OGG are embedded with native browser playback controls.</span></div><div class="file-type"><strong>PDF</strong><span class="muted">PDF reports are embedded directly in the artifact view for quick inspection.</span></div><div class="file-type"><strong>Other files</strong><span class="muted">Files that cannot be safely previewed are still listed with their name and size instead of being hidden.</span></div></div><div class="security-note"><strong>Least-privilege access</strong><div class="muted" style="margin-top:5px">Artifact Lens uses a GitHub App with read-only Metadata + Actions permissions. It can only see repositories where the app is installed and that your GitHub account can access.</div></div><button class="primary" onclick="location.href='/api/auth/login'">Continue with GitHub</button></div>`}
async function boot(){try{const me=await api('/api/me');account.innerHTML=`<div class="login"><img class="avatar" src="${esc(me.avatar_url)}" alt=""><span>${esc(me.login)}</span><button onclick="refreshCurrent()">Refresh</button><button onclick="location.href='/api/auth/logout'">Log out</button></div>`;await restoreFromRoute()}catch(e){if(e.message!=='AUTH'){err.textContent=e.message;renderLogin()}}}
async function showRepos(opt={}){closeLightbox();S={repo:null,branch:null,run:null,artifact:null};if(!opt.preserveRoute)setRoute(opt.replace);app.innerHTML='<div class="muted">Loading repositories…</div>';try{const data=await api('/api/repos'),repos=data.repositories||[],install=data.install_available?`<button onclick="openInstallPopup()">Install / add repositories</button>`:'';const list=repos.length?`<div class="grid">${repos.map(r=>`<div class="repo" onclick="pickRepoEncoded('${enc(r.full_name)}')"><div class="row"><strong>${esc(r.full_name)}</strong>${r.private?'<span class="badge">private</span>':''}</div><div class="muted" style="margin-top:8px">${esc(r.description||'No description')}</div><div class="muted" style="margin-top:10px;font-size:12px">Updated ${ago(r.updated_at)}</div></div>`).join('')}</div>`:`<div style="padding:28px 8px;text-align:center"><h3>No installed repositories</h3><p class="muted">Install Artifact Lens on one or more repositories, then refresh this list.</p>${install}</div>`;app.innerHTML=`<div class="row"><div><h2 style="margin:0">Repositories</h2><div class="muted">Repositories available through your GitHub App installations.</div></div><div class="actions"><button onclick="refreshCurrent()">Refresh</button>${install}</div></div><div style="margin:16px 0"><input placeholder="owner/repository" onkeydown="if(event.key==='Enter')pickRepo(this.value)"></div>${list}`;return repos}catch(e){err.textContent=e.message}}
window.openInstallPopup=function(){const w=Math.min(960,screen.availWidth-40),h=Math.min(820,screen.availHeight-80),l=Math.max(0,Math.round((screen.availWidth-w)/2)),t=Math.max(0,Math.round((screen.availHeight-h)/2)),p=window.open('/api/auth/install','artifactLensGitHubInstall',`popup=yes,width=${w},height=${h},left=${l},top=${t},resizable=yes,scrollbars=yes`);if(!p){err.textContent='The GitHub installation popup was blocked by your browser. Allow popups for this site and try again.';return}p.focus();const timer=setInterval(()=>{if(p.closed){clearInterval(timer);showRepos({replace:true})}},700)};
window.pickRepo=async function(repo,opt={}){repo=String(repo).trim();if(!/^[^/]+\/[^/]+$/.test(repo))return;closeLightbox();S={repo,branch:null,run:null,artifact:null};if(!opt.preserveRoute)setRoute(opt.replace);app.innerHTML='<div class="muted">Finding branches with artifacts…</div>';try{const rows=await api('/api/repo/branches?repo='+encodeURIComponent(repo));app.innerHTML=crumbs()+`<div class="row"><h2>Branches with artifacts</h2><button onclick="refreshCurrent()">Refresh</button></div><div class="grid">${rows.map(b=>`<div class="branch" onclick="pickBranchEncoded('${enc(b.branch)}')"><div class="row"><strong>${esc(b.branch)}</strong><span class="badge">${b.count} artifacts</span></div><div class="muted" style="margin-top:8px">Last artifact ${ago(b.updated_at)}</div></div>`).join('')||'<div class="muted">No artifacts found.</div>'}</div>`;return rows}catch(e){err.textContent=e.message}};
window.pickBranch=async function(branch,opt={}){closeLightbox();S.branch=String(branch);S.run=null;S.artifact=null;if(!opt.preserveRoute)setRoute(opt.replace);app.innerHTML='<div class="muted">Loading workflow runs…</div>';try{const runs=await api('/api/repo/runs?repo='+encodeURIComponent(S.repo)+'&branch='+encodeURIComponent(S.branch));app.innerHTML=crumbs()+`<div class="row"><h2>Runs</h2><button onclick="refreshCurrent()">Refresh</button></div><div class="grid">${runs.map(r=>{const s=r.conclusion||r.status;return`<div class="run" onclick="pickRunEncoded('${pack(r)}')"><div class="row"><strong>${esc(r.name)}</strong><span class="badge ${statusClass(s)}">${esc(s)}</span></div><div class="muted" style="margin-top:8px">${ago(r.updated_at)} · ${r.artifacts.length} artifact${r.artifacts.length!==1?'s':''}</div><div class="muted" style="margin-top:6px;font-size:12px">${esc(r.head_sha.slice(0,8))}</div></div>`}).join('')||'<div class="muted">No artifact-bearing runs found.</div>'}</div>`;return runs}catch(e){err.textContent=e.message}};
window.pickRun=function(run,opt={}){closeLightbox();S.run=run;S.artifact=null;if(!opt.preserveRoute)setRoute(opt.replace);app.innerHTML=crumbs()+`<div class="row"><h2>${esc(run.name)}</h2><button onclick="refreshCurrent()">Refresh</button></div><div class="grid">${run.artifacts.map(a=>`<div class="artifact" onclick="pickArtifactEncoded('${pack(a)}')"><strong>${esc(a.name)}</strong><div class="muted" style="margin-top:8px">${(a.size_in_bytes/1048576).toFixed(1)} MB · ${ago(a.updated_at)}</div></div>`).join('')}</div>`};
window.pickArtifact=async function(artifact,opt={}){closeLightbox();S.artifact=typeof artifact==='object'?artifact:{id:String(artifact),name:`Artifact ${artifact}`};if(!opt.preserveRoute)setRoute(opt.replace);app.innerHTML=crumbs()+`<h2>${esc(S.artifact.name)}</h2><div class="muted">Inspecting artifact…</div>`;try{const id=S.artifact.id,files=await api(`/api/repo/artifact?repo=${encodeURIComponent(S.repo)}&id=${encodeURIComponent(id)}`),media=files.filter(x=>x.media),other=files.filter(x=>!x.media);currentImages=media.filter(x=>x.mime.startsWith('image/')).map(f=>({name:f.name,url:`/api/repo/artifact?repo=${encodeURIComponent(S.repo)}&id=${encodeURIComponent(id)}&file=${encodeURIComponent(f.name)}`}));app.innerHTML=crumbs()+`<div class="row"><h2>${esc(S.artifact.name)}</h2><button onclick="refreshCurrent()">Refresh</button></div><div class="media">${media.map(f=>renderMedia(id,f)).join('')||'<div class="muted">No embeddable media detected.</div>'}</div>${other.length?`<h3>Other files</h3><div class="grid">${other.map(f=>`<div class="artifact"><strong>${esc(f.name)}</strong><div class="muted">${Math.round(f.size/1024)} KB</div></div>`).join('')}</div>`:''}`;return files}catch(e){err.textContent=e.message}};
function renderMedia(id,f){const u=`/api/repo/artifact?repo=${encodeURIComponent(S.repo)}&id=${encodeURIComponent(id)}&file=${encodeURIComponent(f.name)}`;let b='';if(f.mime.startsWith('image/'))b=`<img loading="lazy" src="${u}" alt="${esc(f.name)}" onclick="openLightbox(${currentImages.findIndex(x=>x.name===f.name)})">`;else if(f.mime.startsWith('video/'))b=`<video controls preload="metadata" src="${u}"></video>`;else if(f.mime.startsWith('audio/'))b=`<audio controls preload="metadata" src="${u}"></audio>`;else if(f.mime==='application/pdf')b=`<iframe src="${u}" title="${esc(f.name)}"></iframe>`;return`<figure>${b}<figcaption>${esc(f.name)}</figcaption></figure>`}
window.openLightbox=function(i){if(!currentImages.length||i<0)return;lightboxIndex=i;renderLightbox();lightbox.classList.remove('hidden');document.body.style.overflow='hidden'};
function renderLightbox(){const x=currentImages[lightboxIndex];if(!x)return;lightboxImage.src=x.url;lightboxImage.alt=x.name;lightboxMeta.innerHTML=`${esc(x.name)}<span class="lightbox-counter">${lightboxIndex+1} / ${currentImages.length}</span>`;const m=currentImages.length>1;lightboxPrev.style.display=m?'':'none';lightboxNext.style.display=m?'':'none'}
window.lightboxStep=function(d){if(currentImages.length<2)return;lightboxIndex=(lightboxIndex+d+currentImages.length)%currentImages.length;renderLightbox()};window.closeLightbox=function(){lightbox.classList.add('hidden');lightboxImage.removeAttribute('src');document.body.style.overflow=''};
lightbox.addEventListener('click',e=>{if(e.target===lightbox)closeLightbox()});lightbox.querySelector('.lightbox-close').addEventListener('click',closeLightbox);lightboxPrev.addEventListener('click',()=>lightboxStep(-1));lightboxNext.addEventListener('click',()=>lightboxStep(1));document.addEventListener('keydown',e=>{if(lightbox.classList.contains('hidden'))return;if(e.key==='Escape')closeLightbox();if(e.key==='ArrowLeft')lightboxStep(-1);if(e.key==='ArrowRight')lightboxStep(1)});
function crumbs(){return`<div class="crumbs"><button onclick="showRepos()">Repositories</button>${S.repo?`<button onclick="pickRepoEncoded('${enc(S.repo)}')">${esc(S.repo)}</button>`:''}${S.branch?`<button onclick="pickBranchEncoded('${enc(S.branch)}')">${esc(S.branch)}</button>`:''}${S.run?`<button onclick="pickRunEncoded('${pack(S.run)}')">Run #${S.run.id}</button>`:''}${S.artifact?`<button onclick="pickArtifactEncoded('${pack(S.artifact)}')">${esc(S.artifact.name)}</button>`:''}</div>`}
window.refreshCurrent=async function(){const a=S.artifact,r=S.run,b=S.branch,p=S.repo;if(a)return pickArtifact(a,{preserveRoute:true});if(r){const runs=await pickBranch(b,{preserveRoute:true}),fresh=(runs||[]).find(x=>String(x.id)===String(r.id));if(fresh)return pickRun(fresh,{preserveRoute:true})}if(b)return pickBranch(b,{preserveRoute:true});if(p)return pickRepo(p,{preserveRoute:true});return showRepos({preserveRoute:true})};
async function restoreFromRoute(){const r=parseRoute();if(!r.repo)return showRepos({replace:true});navigatingHistory=true;try{await pickRepo(r.repo,{preserveRoute:true});if(!r.branch)return;const runs=await pickBranch(r.branch,{preserveRoute:true});if(!r.runId)return;const run=(runs||[]).find(x=>String(x.id)===String(r.runId));if(!run)throw new Error(`Workflow run ${r.runId} was not found on branch ${r.branch}.`);pickRun(run,{preserveRoute:true});if(!r.artifactId)return;const a=run.artifacts.find(x=>String(x.id)===String(r.artifactId));if(!a)throw new Error(`Artifact ${r.artifactId} was not found in run ${r.runId}.`);await pickArtifact(a,{preserveRoute:true})}catch(e){err.textContent=e.message}finally{navigatingHistory=false}}
window.addEventListener('popstate',()=>restoreFromRoute());window.showRepos=showRepos;boot();